#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use App\Parser;
use App\File;

$products = (new Parser())
    ->loadRecords()
    ->loadProducts()
    ->getProducts();

File::saveAsJson($products, 'products');